### Init Different Types of Array

In [2]:
import numpy as np

In [3]:
# All zero matrix
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3, 5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros(((2, 3, 5))) 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [6]:
np.ones((4, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [7]:
np.full((2, 2), 99 ,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [8]:
# Any other number (full line)
a = np.array([[
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])

In [9]:
np.full(a.shape, 7)
# or
np.full_like(a, 7)

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [10]:
# Random decimal number
np.random.rand(4, 2, 3)

array([[[0.9941225 , 0.13742166, 0.86790917],
        [0.07516386, 0.52502033, 0.25266454]],

       [[0.2082002 , 0.30140666, 0.35010884],
        [0.65305327, 0.8269903 , 0.56228257]],

       [[0.18567796, 0.33962767, 0.00133286],
        [0.44775186, 0.51269307, 0.51575337]],

       [[0.05124366, 0.87645826, 0.82761271],
        [0.37646048, 0.94067575, 0.17991275]]])

In [11]:
np.random.random_sample(a.shape)

array([[[0.07856768, 0.26053781, 0.51483162],
        [0.42387699, 0.61972406, 0.1426345 ]],

       [[0.96138646, 0.50748781, 0.34152977],
        [0.18059965, 0.61809129, 0.88388392]]])

In [12]:
# Random interger value
np.random.randint(2,5, size=(3, 3))


array([[2, 2, 2],
       [3, 2, 4],
       [2, 4, 3]])

In [13]:
# Idemtity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3) 
print(r1)

[1 1 1 2 2 2 3 3 3]


In [15]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0) 
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
arr = np.ones((5, 5), dtype='int8')
arr[1:4, 1:4] = 0 # or arr[1:-1, 1:-1]
arr[2, 2] = 9
arr 

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

Be Careful when copying array

In [17]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]
