### Init Different Types of Array

In [1]:
import numpy as np

In [2]:
# All zero matrix
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3, 5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.zeros(((2, 3, 5))) 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [5]:
np.ones((4, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [6]:
np.full((2, 2), 99 ,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [7]:
# Any other number (full line)
a = np.array([[
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])

In [8]:
np.full(a.shape, 7)
# or
np.full_like(a, 7)

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [9]:
# Random decimal number
np.random.rand(4, 2, 3)

array([[[0.86497166, 0.95057155, 0.48127389],
        [0.50886789, 0.96627873, 0.83376931]],

       [[0.82971119, 0.10497775, 0.85612963],
        [0.96039173, 0.39334776, 0.08833482]],

       [[0.89399866, 0.94024657, 0.47911128],
        [0.78944651, 0.9636987 , 0.36114822]],

       [[0.45908923, 0.55036396, 0.08565676],
        [0.43866531, 0.75630418, 0.25320731]]])

In [10]:
np.random.random_sample(a.shape)

array([[[0.49083795, 0.770796  , 0.85779278],
        [0.47145873, 0.25026926, 0.29905364]],

       [[0.24369034, 0.51473604, 0.1076235 ],
        [0.33643852, 0.90640243, 0.11810916]]])

In [11]:
# Random interger value
np.random.randint(2,5, size=(3, 3))


array([[4, 2, 2],
       [3, 3, 3],
       [2, 3, 2]])

In [12]:
# Idemtity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3) 
print(r1)

[1 1 1 2 2 2 3 3 3]


In [14]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0) 
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [15]:
arr = np.ones((5, 5), dtype='int8')
arr[1:4, 1:4] = 0 # or arr[1:-1, 1:-1]
arr[2, 2] = 9
arr 

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

Be Careful when copying array

In [16]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]
