### Init Different Types of Array

In [10]:
import numpy as np

In [11]:
# All zero matrix
np.zeros(5) 



array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3, 5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros(((2, 3, 5))) 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
np.ones((4, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [16]:
np.full((2, 2), 99 ,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other number (full line)