### Init Different Types of Array

In [2]:
import numpy as np

In [3]:
# All zero matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros(((2, 3, 5)))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [6]:
np.ones((4, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [7]:
np.full((2, 2), 99 ,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [8]:
# Any other number (full line)
a = np.array([[
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

a.shape

(2, 2, 3)

In [9]:
np.full(a.shape, 7)
# or
np.full_like(a, 7)

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [10]:
# Random decimal number
np.random.rand(4, 2, 3)

array([[[0.66926802, 0.02812425, 0.28909217],
        [0.96083217, 0.17156162, 0.82744654]],

       [[0.70804427, 0.13071007, 0.92284281],
        [0.335901  , 0.84321624, 0.84459193]],

       [[0.32671473, 0.89786643, 0.10435307],
        [0.31229668, 0.82476055, 0.66635921]],

       [[0.21887631, 0.97802032, 0.19411456],
        [0.94098711, 0.57439965, 0.3946315 ]]])

In [11]:
np.random.random_sample(a.shape)

array([[[0.78930579, 0.33715765, 0.40375889],
        [0.95629745, 0.0219188 , 0.08383715]],

       [[0.95860773, 0.14526352, 0.74627076],
        [0.46365706, 0.96670839, 0.44769966]]])

In [12]:
# Random interger value
np.random.randint(2,5, size=(3, 3))


array([[2, 2, 3],
       [2, 4, 2],
       [2, 2, 2]])

In [13]:
# Idemtity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [15]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
arr = np.ones((5, 5), dtype='int8')
arr[1:4, 1:4] = 0 # or arr[1:-1, 1:-1]
arr[2, 2] = 9
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

Be Careful when copying array

In [17]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]
