### Init Different Types of Array

In [49]:
import numpy as np

In [50]:
# All zero matrix
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((3, 5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
np.zeros(((2, 3, 5))) 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [53]:
np.ones((4, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [54]:
np.full((2, 2), 99 ,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [55]:
# Any other number (full line)
a = np.array([[
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])

In [56]:
np.full(a.shape, 7)
# or
np.full_like(a, 7)

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [57]:
# Random decimal number
np.random.rand(4, 2, 3)

array([[[0.94236263, 0.34132772, 0.26712872],
        [0.33850939, 0.69464476, 0.72176123]],

       [[0.74494152, 0.89066161, 0.97473064],
        [0.19774018, 0.90811099, 0.32875558]],

       [[0.57659146, 0.29195611, 0.08360147],
        [0.16866818, 0.56734583, 0.83091527]],

       [[0.99737848, 0.18842552, 0.47739275],
        [0.10585865, 0.26673248, 0.19308022]]])

In [58]:
np.random.random_sample(a.shape)

array([[[0.29994662, 0.12539014, 0.70777049],
        [0.10016223, 0.23016771, 0.60148006]],

       [[0.53450159, 0.19213508, 0.88757395],
        [0.72629787, 0.6468584 , 0.27360789]]])

In [59]:
# Random interger value
np.random.randint(2,5, size=(3, 3))


array([[4, 3, 4],
       [4, 3, 2],
       [3, 2, 2]])

In [60]:
# Idemtity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3) 
print(r1)

[1 1 1 2 2 2 3 3 3]


In [62]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0) 
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [84]:
arr = np.ones((5, 5), dtype='int8')
arr[1:4, 1:4] = 0 # or arr[1:-1, 1:-1]
arr[2, 2] = 9
arr 

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

Be Careful when copying array

In [87]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[100   2   3]
