In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3, 7],
              [4, 5, 6, 7]])

print(a)
print(b)

[1 2 3]
[[1 2 3 7]
 [4 5 6 7]]


In [2]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [3]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [4]:
# Get Type
print(a.dtype)
print(b.dtype)

int64
int64


In [5]:
# Changing the dtype from int64 - int32 or int16
a = np.array([1, 2, 3], dtype="int32")
a.dtype


dtype('int32')

In [6]:
# Get size
print(a.itemsize)  # Output in bytes
print(a.itemsize)

4
4


In [7]:
# Get total size
print(a.size)
print(b.size)

3
8


In [8]:
# a.itemsize * a.size
print(a.nbytes)
print(b.nbytes)

12
64


In [9]:
# Get a Specific row
print(b[0, :])

[1 2 3 7]


In [10]:
# Get a Specific Column
print(b[:, 2])

[3 6]


In [11]:
# [start_i, end_i, steps_i]
print(b[0, 1:])

[2 3 7]


In [12]:
# Changing value
print(f"b before:\n {b}")
b[0, 1] = -2
print(f"b after:\n {b}")

b before:
 [[1 2 3 7]
 [4 5 6 7]]
b after:
 [[ 1 -2  3  7]
 [ 4  5  6  7]]


In [13]:
# Making specific columns value
b[:, 1] = 2
print(b)

[[1 2 3 7]
 [4 2 6 7]]


In [16]:
array_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])

print(array_3d[0, 1, 2]) # Specific element
print(array_3d[0, 1, :]) # Specific row
print(array_3d[:, :, 1]) # Specific column 

6
[4 5 6]
[[ 2  5]
 [ 8 11]]
