In [76]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [77]:
a + 2
a - 2
a * 2
a // 2

array([0, 1, 1, 2])

In [78]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [79]:
# Take the sin
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

In [83]:
a = np.ones((2,3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [85]:
# Find the Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# https://numpy.org/doc/stable/reference/routines.linalg.html