In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [11]:
a + 2
a - 2
a * 2
a // 2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [10]:
# Take the sin
np.sin(a)
np.cos(a)

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

## Linear Algebra

In [5]:
a = np.ones((2,3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [15]:
# Find the Determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [7]:
# https://numpy.org/doc/stable/reference/routines.linalg.html