### Reorganizing array

In [3]:
import numpy as np

In [12]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print("---------")
after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
---------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
# Vertically Stacking
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
v3 = np.array([9, 10, 11, 12])

np.stack([v1, v2, v3])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# Horizontal Stacking
h1 = np.zeros((2, 4))
h2 = np.ones((2, 4))

np.hstack((h1, h2))

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])